import { NextResponse } from 'next/server';
import { addSubmission, type Submission } from '@/lib/db';
import { normalizeGrid, formatHash } from '@/lib/sudoku';
import crypto from 'crypto';

export async function POST(req: Request) {
    try {
        const body = await req.json();
        const { grid } = body;

        if (!grid || !Array.isArray(grid) || grid.length !== 81) {
            return NextResponse.json({ error: "Invalid grid format" }, { status: 400 });
        }

        const gridString = normalizeGrid(grid);

        // Server-side SHA-256 (Node crypto)
        const hash = crypto.createHash('sha256').update(gridString).digest('hex').toUpperCase();

        // Use the actual exported helper from lib/db.ts
        // This helper handles the uniqueness check and saving internally
        const result = addSubmission(gridString, hash);

        if (!result.success) {
            return NextResponse.json({
                error: result.message || "Duplicate! This exact puzzle was already found in the vault.",
                originalId: result.existingId
            }, { status: 409 });
        }

        // Return Success using the ID generated by addSubmission
        const formattedHash = formatHash(result.id!, hash);
        return NextResponse.json({
            success: true,
            id: result.id,
            hash: formattedHash
        });

    } catch (error) {
        console.error("Submit error:", error);
        return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
    }
}
